version: "3.8"

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./clickhouse/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  consumer:
    environment:
      - PYTHONPATH=/app
    build: .
    command: python consumer/main.py
    depends_on:
      - clickhouse
    volumes:
      - ./:/app
    env_file:
      - .env
    restart: unless-stopped

